project:
  type: book
  output-dir: docs

book:
  google-analytics: G-NRY8TV1Q8G
  title: "Disease outbreaks and metrics"
  repo-url: https://github.com/cmilando/RtEstimBook
  page-footer: Reproductive Number R(t) - [https://chadmilando.com/RtEstimBook/](https://chadmilando.com/RtEstimBook/){target="_blank"}
  repo-branch: main
  repo-actions: [edit]
  site-url: https://chadmilando.com/RtEstimBook/
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - simulation_tool.qmd
    - decisiontree.qmd
    - part: methods.qmd
      chapters:
        - methods_introduction.qmd
        - methods_distributions.qmd
        - methods_time.qmd
        - methods_additionaldata.qmd
        - methods_inference.qmd
        - methods_research.qmd
    - part: packages.qmd
      chapters:
      - package_APEestim.qmd
      - package_bayEStim.qmd
      - package_earlyR.qmd
      - package_Epidemia.qmd
      - package_EpiEstim.qmd
      - package_EpiFilter.qmd
      - package_EpiFusion.qmd
      - package_epigrowthfit.qmd
      - package_EpiInvert.qmd
      - package_EpiLPS.qmd
      - package_EpiNow2.qmd
      - package_epinowcast.qmd
      - package_ern.qmd
      - package_EstimateR.qmd
      - package_R0.qmd
      - package_RtEstim.qmd
      - package_WhiteLabRt.qmd
    - glossary.qmd
    - references.qmd

bibliography: references.bib
csl: nature.csl

format:
  html:
    theme:
      - cosmo
      - markdown-style.scss
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png



